default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: task_development

test:
  <<: *default
  database: task_test

production:
  <<: *default
  database: task_production
  username: task
  password: <%= ENV['TASK_DATABASE_PASSWORD'] %>
