# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d63f602aaccb0dd4ea838c73a6cf1ef132e858b8882f1e8fd312fe500ce96aca0e634ef34ac86ae39350dc6a4268e1aee7f44b8b6acb3e4cc354a5c2fe7fc3f

test:
  secret_key_base: 99d42a166b94bab768ebe9b86be6bdf0e7ead4e7e4ba65f57c74136eb015c203fdb87b46abe3b4781291e5b7d552465e4f057e4b2b2a5dc7d1b0fc0c95df5129

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
